/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "STM32F103C8T6.h"
#include "STM32F103C8T6_GPIO_Driver.h"


int main(void)
{
	GPIO_HANDLE_t pGPIOC_Handle;
	pGPIOC_Handle.pGPIOx = pGPIOC;
	pGPIOC_Handle.GPIO_PinConFig.GPIO_PinNumber = GPIO_NO_13;
	pGPIOC_Handle.GPIO_PinConFig.GPIO_PinMode = GPIO_MODE_OUT_LOW;
	pGPIOC_Handle.GPIO_PinConFig.GPIO_PinConfiguration = GPIO_OMODE_PP;

	GPIO_ClkControl(pGPIOC_Handle.pGPIOx, ENABLE);
	GPIO_Init(&pGPIOC_Handle);
	while(1){
		GPIO_ToggleOutPutPin(pGPIOC_Handle.pGPIOx, pGPIOC_Handle.GPIO_PinConFig.GPIO_PinNumber);
		//GPIO_ToggleOutPutPin(pGPIOC_Handle.pGPIOx, pGPIOC_Handle.GPIO_PinConFig.GPIO_PinNumber);
		for(uint32_t i =0;i<500000;i++);
	}

}
